# Generated by Django 4.2.7 on 2023-12-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_category_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Інгредіент', 'verbose_name_plural': 'Інгредіенти'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Назва', 'verbose_name_plural': 'Назви'},
        ),
    ]
